apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "guestbook-basic.common-labels" . | indent 4 }}
    "app.kubernetes.io/component": frontend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.guestbookReplicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: php-redis
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
{{ .Values.resources | toYaml | indent 10 }}
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: {{ .Release.Name }}-redis-master
        - name: REDIS_SLAVE_SERVICE_HOST
          value: {{ .Release.Name }}-redis-slave
{{- if .Values.healthchecks.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.healthchecks.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                ! curl 'localhost:{{ .Values.healthchecks.port }}/guestbook.php?cmd=get&key=messages' | grep 'ConnectionException'
          initialDelaySeconds: 3
          periodSeconds: 5
{{- end }}
        ports:
{{- range .Values.servicePorts }}
        - containerPort: {{ . }}
{{- end }}
