{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guestbook.serviceAccountName" . }}
  labels:
{{ include "guestbook.labels" . | nindent 4 }}
{{- end -}}
