apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-master
  labels:
{{ include "guestbook.common-labels" . | indent 4 }}
    "app.kubernetes.io/component": backend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis-master
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
