apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-slave
  labels:
{{ include "guestbook.common-labels" . | indent 4 }}
    "app.kubernetes.io/component": backend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis-slave
  replicas: {{ .Values.redisReplicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis-slave
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: {{ .Release.Name }}-redis-master
        ports:
        - containerPort: 6379
